import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
  Code,
  Flex,
  IconButton,
  Text,
  useClipboard,
} from "@chakra-ui/react";

import { FiCopy } from "react-icons/fi";

function SqlAccordion({ sql }) {

  const { hasCopied, onCopy } =
    useClipboard(sql || "");

  if (!sql) return null;

  return (
    <Accordion
      allowToggle
      mt={3}
    >
      <AccordionItem
        border="1px solid"
        borderColor="gray.200"
        borderRadius="lg"
      >

        <AccordionButton>

          <Box
            flex="1"
            textAlign="left"
            fontWeight="600"
          >
            Generated SQL
          </Box>

          <AccordionIcon />

        </AccordionButton>

        <AccordionPanel>

          <Flex
            justify="space-between"
            mb={3}
          >

            <Text
              fontSize="sm"
              color="gray.500"
            >
              SQL generated by AI
            </Text>

            <IconButton
              aria-label="Copy SQL"
              size="sm"
              icon={<FiCopy />}
              onClick={onCopy}
            />

          </Flex>

          <Code
            display="block"
            whiteSpace="pre-wrap"
            p={4}
            borderRadius="lg"
            w="100%"
          >
            {sql}
          </Code>

          {hasCopied && (
            <Text
              mt={2}
              color="green.500"
              fontSize="sm"
            >
              Copied!
            </Text>
          )}

        </AccordionPanel>

      </AccordionItem>
    </Accordion>
  );
}

export default SqlAccordion;